---
title: "graphs"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DiagrammeR)
library(reshape2)
library(here)
library(knitr)
library(patchwork)

dhs <- read_csv(here::here("inputs/data/cleaned_data.csv"), show_col_types = FALSE)
```

Graphs
```{r}
# Illiterate females get married early
dhs %>%
  ggplot(aes(`Percent of illiterate females`, `Percent of women married before age 18`, color = States)) +
  geom_point()

# Illiteracy has no connection to contraceptives? 
dhs %>%
  ggplot(aes(`Percent of illiterate females`, `Percent of women using any contraceptive method`)) +
  geom_point() +
  geom_smooth(method = "lm")

# Women going to school in each state
dhs %>%
  ggplot(aes(x=States, y=`Percent of females attending schools`)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
  #theme(axis.text.x = element_text(angle = 90))

#Unmet family planning leading to infant mortality or under 5 mortality are apparently not related
dhs %>%
  ggplot(aes(`Unmet need for family planning`, `Infant mortality rate`)) +
  geom_point()

dhs %>%
  ggplot(aes(`Unmet need for family planning`, `Under 5 mortality`)) +
  geom_point()

#females schools & illerate vs immunization
dhs %>%
  ggplot(aes(`Percent of children who received ORS for diarrhea`, `Percent of children fully immunized`)) +
  geom_point()

dhs %>%
  ggplot(aes(`Percent of illiterate females`, `Percent of children fully immunized`)) +
  geom_point()
```


```{r}
# dhs$`Percent of children who received ORS for diarrhea`[1]
dhs <- dhs %>%
  mutate(nigib1 = case_when(
    `Percent of illiterate females` >= 56.7 ~ 1,
    `Percent of illiterate females` < 56.7 ~ -1
  ))
dhs <- dhs %>%
  mutate(nigib2 = case_when(
    `Percent of children who received ORS for diarrhea` >= 30.6 ~ 1,
    `Percent of children who received ORS for diarrhea` < 30.6 ~ -1
  ))

interaction.plot(dhs$nigib1, dhs$nigib2, dhs$`Percent of children fully immunized`)
```

```{r}
DiagrammeR::grViz("
digraph {
  graph [ranksep = 0.2]
  node [shape = plaintext, fontsize = 10, fontname = Helvetica]
    Illiterate
    Antenatal
    Water
    Births
    Immunized
  edge [minlen = 2, arrowhead = vee]
    Illiterate->Immunized
    Illiterate->Births
    Antenatal->Immunized
    Antenatal->Births
    Water->Immunized
    Illiterate->Antenatal
  { rank = same; Immunized; Births }
}
", height = 300)
```


```{r}
#States with household toilet & water pipes
nigib1 <- data.frame(dhs$States, dhs$`Percent of households with drinking water from pipe`, dhs$`Percent of households with no toilet facility`)
colnames(nigib1) <- c("States", "Water", "Toilets")
nigib2 <- reshape2::melt(nigib1, id.vars = 'States')


nigib2 %>%
  ggplot(aes(x = States, y = value, fill=variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()
```


```{r}
# Per state, underwight stunted and wasted children
nigib1 <- data.frame(dhs$States, dhs$`Percent of children underweight`, dhs$`Percent of children stunted`, dhs$`Percent of children wasted`)
colnames(nigib1) <- c("States", "Underwight", "Stunted", "Wasted")
nigib2 <- reshape2::melt(nigib1, id.vars = 'States')

nigib2 %>%
  ggplot(aes(x = States, y = value, fill=variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()
```

```{r}
tiny_dhs <- dhs %>%
  select(c(1, 2, 4, 14, 16, 19))
```

```{r}
kable(head(tiny_dhs, 5))
```

```{r}
tiny_dhs %>%
  ggplot(aes(`Percent of illiterate females`, `Percent of children fully immunized`)) +
  geom_point() +
  geom_smooth(method='lm')
```

```{r}
tiny_dhs %>%
  ggplot(aes(`Percent of mothers receiving antenatal care`, `Percent of births delivered in health facility`)) +
  geom_point() +
  geom_smooth(method='lm')
```

```{r}
tiny_dhs %>%
  ggplot(aes(`Percent of illiterate females`, `Percent of births delivered in health facility`)) +
  geom_point() +
  geom_smooth(method='lm')
```

```{r}
tiny_dhs <- tiny_dhs %>%
  mutate(illiterate = case_when(
    `Percent of illiterate females` >= 56.7 ~ 1,
    `Percent of illiterate females` < 56.7 ~ -1
  ))

tiny_dhs <- tiny_dhs %>%
  mutate(antenatal = case_when(
    `Percent of mothers receiving antenatal care` >= 62.3 ~ 1,
    `Percent of mothers receiving antenatal care` < 62.3 ~ -1
  ))

tiny_dhs <- tiny_dhs %>%
  mutate(water = case_when(
    `Percent of households with drinking water from pipe` >= 68.2 ~ 1,
    `Percent of households with drinking water from pipe` < 68.2 ~ -1
  ))

tiny_dhs <- tiny_dhs %>%
  mutate(births = case_when(
    `Percent of births delivered in health facility` >= 25.5 ~ 1,
    `Percent of births delivered in health facility` < 25.5 ~ -1
  ))

tiny_dhs <- tiny_dhs %>%
  mutate(immunized = case_when(
    `Percent of children fully immunized` >= 35.4 ~ 1,
    `Percent of children fully immunized` < 35.4 ~ -1
  ))
```

```{r}
ip1 <- interaction.plot(tiny_dhs$illiterate, tiny_dhs$antenatal, tiny_dhs$births)
ip2 <- interaction.plot(tiny_dhs$illiterate, tiny_dhs$antenatal, tiny_dhs$immunized)

ip3 <- interaction.plot(tiny_dhs$illiterate, tiny_dhs$water, tiny_dhs$births)
ip4 <- interaction.plot(tiny_dhs$illiterate, tiny_dhs$water, tiny_dhs$immunized)

ip5 <- interaction.plot(tiny_dhs$antenatal, tiny_dhs$water, tiny_dhs$births)
ip6 <- interaction.plot(tiny_dhs$antenatal, tiny_dhs$water, tiny_dhs$immunized)
```


```{r}
# Health facility v/s immunization
view(tiny_dhs)
nigib1 <- data.frame(tiny_dhs$States, tiny_dhs$`Percent of births delivered in health facility`, tiny_dhs$`Percent of children fully immunized`)
colnames(nigib1) <- c("States", "Health Facility", "Immunized")
nigib2 <- reshape2::melt(nigib1, id.vars = 'States')

nigib2 %>%
  ggplot(aes(x = States, y = value, fill=variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()

#Illiterate females v/s antenatal care
nigib1 <- data.frame(tiny_dhs$States, tiny_dhs$`Percent of illiterate females`, tiny_dhs$`Percent of mothers receiving antenatal care`, tiny_dhs$`Percent of households with drinking water from pipe`, tiny_dhs$`Percent of births delivered in health facility`, tiny_dhs$`Percent of children fully immunized`)
colnames(nigib1) <- c("States", "Illiterate Females", "Antenatal Care", "Water", "Births", "Immunized")
nigib2 <- reshape2::melt(nigib1, id.vars = 'States')

nigib2 %>%
  ggplot(aes(x = States, y = value, fill=variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  coord_flip()
```

















